### ISSUE TITLE
ModuleNotFoundError: No module named 'ensembl.production.core'

### ISSUE THREAD

**Issue by nolarifi** [Ensembl/ensembl-prodinf-event#6]
when I run this command line : flask run --port 5000 --host 0.0.0.0
I GET THIS ERROR; ModuleNotFoundError: No module named 'ensembl.production.core'

**Comment by vinay-ebi** [comment]
Hi nolarifi,

Install dependency module ensembl-prodinf-core (https://github.com/Ensembl/ensembl-prodinf-core.git) and try  to run 

export FLASK_APP=ensembl.production.event.app.main.py
flask run --port 5000 --host 0.0.0.0
